## 部署位置
troweb.path: ~/data/apps/tro-web
## 数据库配置
resource:
  ## mysql
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: shulie@2020
  ## redis配置
  ## redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: shulie@2020
  ## influxdb配置
  ## influxdb
  influxdb:
    url: http://127.0.0.1:8086
    user: root
    password: shulie@2020
    database: base

## tro-cloud 访问url配置 具体配置看引入
trocloud.out.url: 127.0.0.1:10010
## 大数据配置
### AMDB 组件提供的请求地址 ###
amdb.url.prdar: 127.0.0.1:8080
amdb.url.amdb: http://127.0.0.1:10032
## 配置zk地址 用与agent交互
tro.config.zk.addr: 127.0.0.1:2181
## 白名单位置
spring.config.whiteListPath: /opt/tro/conf/tro-web/api/confcenter/wbmnt/query/
#文件上传路径，url为外网地址，临时文件和脚本文件需和tro-cloud保持一致，当前路径为云端相关配置
file:
  upload:
    url: http://${trocloud.out.url}/tro-cloud
    tmp.path: ${script.temp.path}
    script.path: ${script.path}
### tro-cloud configs ##
fast.debug.upload.log.path: ~/data/fastdebug/log
fast.debug.call.stack.path: ~/data/fastdebug/callstack
#账号管理相关==>#
file.upload.user.data.dir: ~/data/apps/tro-web
# agent上报tro-web地址
agent.interactive.tro.web.url:  http://127.0.0.1:10008/tro-web


server:
  port: 10008
  servlet:
    context-path: /tro-web
  tomcat:
    basedir: ${troweb.path}
spring:
  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${resource.mysql.host}:${resource.mysql.port}/trodb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: ${resource.mysql.username}
    password: ${resource.mysql.password}
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      filters: stat,wall,slf4j
      test-while-idle: true
      test-on-borrow: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      test-on-return: false
  #redis配置
  redis:
    host: ${resource.redis.host}
    port: ${resource.redis.port}
    password: ${resource.redis.password}
    timeout: 10000
    jedis:
      pool:
        max-idle: 8
        min-idle: 10
        max-active: 100
        max-wait: -1
  resources:
    static-locations: file:${user.dir}/dist
  influxdb:
    url: ${resource.influxdb.url}
    user: ${resource.influxdb.user}
    password: ${resource.influxdb.password}
    database: ${resource.influxdb.database}

remote:
  #云端控制台
  url: http://${trocloud.out.url}/tro-cloud
  client:
    download:
      #文件下载请求url，勿动
      uri: /api/bigfile/download

#场景管理 是否开启jmeter脚本校验
script.check: true
## 是否展示为图
link.graph.enable: false
customer:
  id: 1
  key: 5b06060a-17cb-4588-bb71-edd7f65035af

### tro-cloud configs ##
tro.cloud.url: http://${trocloud.out.url}/tro-cloud
#等大文件上传可以了，这个应该会删除掉
remote.client.download.uri: /api/bigfile/download
logging.level.io.shulie.tro.web.data.dao: DEBUG
link.flow.check.enable: true

